<a href="https://colab.research.google.com/github/gurjeet3010/PyTorch-Learning/blob/main/01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
# to check GPU availability
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


CREATING A TENSOR USING PYTORCH

In [6]:
#   using empty
a = torch.empty(2,3)

In [8]:
# check type
type(a)

torch.Tensor

In [9]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# using rand -> gives random values
torch.rand(2,3)

tensor([[0.0396, 0.7566, 0.7011],
        [0.2635, 0.9825, 0.0774]])

In [13]:
# use of seed -> to fetch same random values we initalize seed value
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# other ways

# arange
print("using arange ->", torch.arange(0,12,2))

# using linspace -> linearly spaced
print("using linspace ->", torch.linspace(0,10,10))

# using eye -> identity matrix -> diagonal matrix
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([ 0,  2,  4,  6,  8, 10])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


TENSOR SHAPES

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [20]:
# to create a duplicate tensor from the existing shape
torch.empty_like(x)

tensor([[1045354573,          0,         64],
        [       112, 1044904877,          0]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)

TENSORS DATA TYPES

In [24]:
# find data types
x.dtype

torch.int64

In [25]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3], dtype = torch.float32)

tensor([1., 2., 3.])

In [28]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])