<a href="https://colab.research.google.com/github/gurjeet3010/PyTorch-Learning/blob/main/02_Tensors_Mathematical_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
print(torch.__version__)

2.11.0+cpu


1. Scalar Operations

In [9]:
x = torch.rand(2,2)
x

tensor([[0.9676, 0.7205],
        [0.5626, 0.8205]])

In [10]:
# addition
x + 15

tensor([[15.9676, 15.7205],
        [15.5626, 15.8205]])

In [11]:
# substraction
x - 3

tensor([[-2.0324, -2.2795],
        [-2.4374, -2.1795]])

In [12]:
# multiplication
x * 2

tensor([[1.9352, 1.4411],
        [1.1251, 1.6411]])

In [13]:
# division
x / 10

tensor([[0.0968, 0.0721],
        [0.0563, 0.0821]])

In [14]:
# mod
((x * 100) // 3) % 2

tensor([[0., 0.],
        [0., 1.]])

In [15]:
# power
(((x * 100) // 3) % 2) ** 2

tensor([[0., 0.],
        [0., 1.]])

2. Element Wise Operation

In [16]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4429, 0.4580, 0.6034],
        [0.2445, 0.7410, 0.7018]])
tensor([[0.2768, 0.6133, 0.4959],
        [0.9251, 0.8653, 0.8733]])


In [17]:
# add
a + b

tensor([[0.7197, 1.0713, 1.0992],
        [1.1695, 1.6063, 1.5751]])

In [18]:
# substraction
a - b

tensor([[ 0.1660, -0.1554,  0.1075],
        [-0.6806, -0.1242, -0.1715]])

In [19]:
# multiplication
a * b

tensor([[0.1226, 0.2809, 0.2992],
        [0.2261, 0.6412, 0.6129]])

In [20]:
# division
a / b

tensor([[1.5998, 0.7467, 1.2168],
        [0.2642, 0.8564, 0.8037]])

In [21]:
# power
a ** b

tensor([[0.7981, 0.6194, 0.7784],
        [0.2717, 0.7716, 0.7340]])

In [22]:
# mod
a % b

tensor([[0.1660, 0.4580, 0.1075],
        [0.2445, 0.7410, 0.7018]])

In [23]:
c = torch.tensor([1,-2,3,-4])

In [24]:
# abs -> absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [25]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [26]:
d = torch.tensor([1.9, 2.3, 3.7, 4.5])

In [27]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [28]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [29]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [30]:
# clamp -> no lesser then min will turnt into min val and vice versa for max val
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction Operation

In [31]:
e = torch.randint(size=(2,3), low = 0, high = 10, dtype=torch.float32)
e

tensor([[5., 2., 0.],
        [7., 1., 8.]])

In [32]:
# sum
torch.sum(e)

tensor(23.)

In [33]:
# sum along columns
torch.sum(e, dim =0)

tensor([12.,  3.,  8.])

In [34]:
# sum along rows
torch.sum(e, dim = 1)

tensor([ 7., 16.])

In [35]:
# mean
torch.mean(e)

# mean along columns
torch.mean(e, dim =0)

# mean along rows
torch.mean(e, dim = 1)

tensor([2.3333, 5.3333])

In [36]:
# median
torch.median(e)

tensor(2.)

In [37]:
# max and min
maxi = torch.max(e)
mini = torch.min(e)

print("MAX :", maxi)
print("MIN :", mini)

MAX : tensor(8.)
MIN : tensor(0.)


In [38]:
# product
torch.prod(e)

tensor(0.)

In [39]:
# standard deviation
torch.std(e)

tensor(3.3116)

In [40]:
# variance
torch.var(e)

tensor(10.9667)

In [41]:
# argmax -> position of max value
torch.argmax(e)

tensor(5)

In [42]:
# argmin -> position of min value
torch.argmin(e)

tensor(2)

4. Matrix Operations

In [43]:
f = torch.randint(size=(2,3), low = 0, high = 10)
g = torch.randint(size=(3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[6, 8, 6],
        [7, 9, 6]])
tensor([[4, 0],
        [3, 5],
        [3, 7]])


In [44]:
# matrix multiplication
torch.matmul(f, g)

tensor([[66, 82],
        [73, 87]])

In [45]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [46]:
# transpose
torch.transpose(f, 0 ,1)

tensor([[6, 7],
        [8, 9],
        [6, 6]])

In [47]:
h = torch.randint(size=(3,3), low = 0, high = 10, dtype = torch.float32)
h

tensor([[7., 5., 9.],
        [6., 6., 2.],
        [3., 3., 2.]])

In [48]:
# determinant
torch.det(h)

tensor(12.0000)

In [49]:
# inverse
torch.inverse(h)

tensor([[ 0.5000,  1.4167, -3.6667],
        [-0.5000, -1.0833,  3.3333],
        [ 0.0000, -0.5000,  1.0000]])

5. Comparison Operations

In [50]:
i = torch.randint(size=(2,3), low = 0, high = 10)
j = torch.randint(size=(2,3), low = 0, high = 10)

print(i)
print(j)

tensor([[9, 2, 8],
        [6, 3, 9]])
tensor([[8, 7, 2],
        [8, 3, 1]])


In [56]:
# greater than
i > j

# less than
i < j

# not equal to
i != j

# greater than equal to
i >= j

# lesser than equal to
i <= j

tensor([[False,  True, False],
        [ True,  True, False]])

6. Special Functions

In [68]:
k = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float32)
k

tensor([[1., 6., 6.],
        [4., 4., 6.]])

In [58]:
# log
torch.log(k)

tensor([[1.7918, 2.1972, 2.1972],
        [1.0986,   -inf, 2.1972]])

In [59]:
# exp
torch.exp(k)

tensor([[4.0343e+02, 8.1031e+03, 8.1031e+03],
        [2.0086e+01, 1.0000e+00, 8.1031e+03]])

In [60]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 3.0000, 3.0000],
        [1.7321, 0.0000, 3.0000]])

In [61]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9999, 0.9999],
        [0.9526, 0.5000, 0.9999]])

In [69]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0474, 0.8808, 0.5000],
        [0.9526, 0.1192, 0.5000]])

In [70]:
# relu
torch.relu(k)

tensor([[1., 6., 6.],
        [4., 4., 6.]])

Inplace Operations

In [71]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.3622, 0.5540, 0.2904],
        [0.5265, 0.3538, 0.2363]])
tensor([[0.2075, 0.5812, 0.9015],
        [0.1301, 0.8015, 0.1454]])


In [73]:
m.add_(n)

tensor([[0.5696, 1.1351, 1.1919],
        [0.6565, 1.1553, 0.3818]])

In [77]:
torch.relu(m)

tensor([[0.5696, 1.1351, 1.1919],
        [0.6565, 1.1553, 0.3818]])

In [79]:
# for inplace operations add "_" in the end -> it keeps changes permanent
m.relu_()

tensor([[0.5696, 1.1351, 1.1919],
        [0.6565, 1.1553, 0.3818]])

In [80]:
m

tensor([[0.5696, 1.1351, 1.1919],
        [0.6565, 1.1553, 0.3818]])

Copying a Tensor

In [82]:
a = torch.rand(2,3)
a

tensor([[0.9242, 0.6911, 0.6901],
        [0.2934, 0.0314, 0.7755]])

In [85]:
# using this assignment the changes made in a will be same to b
b = a

In [84]:
b

tensor([[0.9242, 0.6911, 0.6901],
        [0.2934, 0.0314, 0.7755]])

In [86]:
id(a)

140060400480848

In [87]:
id(b)

140060400480848

In [89]:
#  using this the changes to a will not affect b
b = a.clone()

In [90]:
a

tensor([[0.9242, 0.6911, 0.6901],
        [0.2934, 0.0314, 0.7755]])

In [91]:
b

tensor([[0.9242, 0.6911, 0.6901],
        [0.2934, 0.0314, 0.7755]])

In [93]:
a[0][0] = 10
a

tensor([[10.0000,  0.6911,  0.6901],
        [ 0.2934,  0.0314,  0.7755]])

In [94]:
b

tensor([[0.9242, 0.6911, 0.6901],
        [0.2934, 0.0314, 0.7755]])