<a href="https://colab.research.google.com/github/gurjeet3010/PyTorch-Learning/blob/main/03_Tensor_Operations__GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [5]:
# creating a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.7616, 0.3052, 0.5539],
        [0.3565, 0.8389, 0.9210]], device='cuda:0')

In [6]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.5403, 0.5920, 0.8443],
        [0.4861, 0.4692, 0.3087]])

In [7]:
b = a.to(device)

In [8]:
b + 5

tensor([[5.5403, 5.5920, 5.8443],
        [5.4861, 5.4692, 5.3087]], device='cuda:0')

In [9]:
import time

# define the size of the metrics
size = 10000 #large size for performance comparison

# create random matrics on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) #matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# move matrics to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) #matrix multiplication on GPU
torch.cuda.synchronize() #ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 16.7726 seconds
Time on GPU: 0.6233 seconds

Speedup (CPU time / GPU time): 26.907267660452383


Reshaping Tensors

In [10]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [12]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
b=torch.rand(2,3,4)
b

tensor([[[0.9040, 0.2601, 0.3468, 0.5978],
         [0.2813, 0.1643, 0.0749, 0.4074],
         [0.4543, 0.0103, 0.7446, 0.6794]],

        [[0.6798, 0.8642, 0.9104, 0.5769],
         [0.4906, 0.7021, 0.0400, 0.4108],
         [0.8219, 0.6267, 0.4328, 0.4668]]])

In [17]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [22]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [23]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

NumPy and PyTorch

In [24]:
import numpy as np

In [25]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [26]:
b = a.numpy()

In [27]:
b

array([1, 2, 3])

In [28]:
type(b)

numpy.ndarray

In [29]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [30]:
torch.from_numpy(c)

tensor([1, 2, 3])